apiVersion: v1
kind: Secret
metadata:
  name: vault-token-secret
type: Opaque
data:
  # {{ with secret "kv/data/VAULT" }}
  VAULT_ADDR: {{ .Data.data.VAULT_ADDR_BASE64ENCODED }}
  VAULT_TOKEN: {{ .Data.data.VAULT_TOKEN_BASE64ENCODED }}
  # {{ with secret "kv/data/VAULT" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-api
  labels:
    app: spring-boot-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-api
  template:
    metadata:
      labels:
        app: spring-boot-api
    spec:
      imagePullSecrets:
        - name: ecr-docker-login-token-from-action
      containers:
        - name: spring-boot-api
          image: id-here.dkr.ecr.us-east-2.amazonaws.com/java/spring-boot-api:2023.10.27.068335443
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod'
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-token-secret
                  key: VAULT_ADDR
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token-secret
                  key: VAULT_TOKEN
          ports:
            - name: apiweb
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api-clusterip
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 80
  selector:
    app: spring-boot-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-api-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  defaultBackend:
    service:
      name: spring-boot-api-clusterip
      port:
        number: 80
  tls:
    - hosts:
        - spring-boot-api.ferozfaiz.com
      secretName: ferozfaiz-com-cloudflare-tls
  rules:
    - host: spring-boot-api.ferozfaiz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot-api-clusterip
                port:
                  number: 80