logging:
  level:
    org:
      springframework: DEBUG

spring:
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_MASTER_HOST}/springboot?currentSchema=dev
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: dev
    drop-first: false
    # Uncomment the following line to drop the database before running migrations
#    drop-first: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# in dev only
server:
  tomcat:
    relaxedQueryChars:
      - '['
      - ']'