logging:
  level:
    org:
      springframework: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_MASTER_HOST}/springboot
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver