logging:
  level:
    org:
      springframework: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_MASTER_HOST}/springboot?currentSchema=public
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: public
    drop-first: false

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect